[project]
name = "unicodeplots"
version = "0.1.0"
description = "UnicodePlots.jl but in python "
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.1.0",
    "ruff>=0.11.0",
]
